import React, { useEffect, useState } from "react";
import SideNavbar from "../components/SideNavBar";
import Head from "next/head";
import Pagination from "../components/Pagination";
import Image from "next/image";
import { Result } from "postcss";
import Footer from "../components/Footer";

export const getStaticProps = async () => {
  const API_URL = "https://screening.moduit.id/frontend/web/question/two";
  const request = await fetch(API_URL);
  const data = await request.json();
  return { props: { data } };
};

export default function question2({ data }) {
  const [currentPage, setCurrentPage] = useState(1);
  const [postsPerPage, setPostsPerPage] = useState(8);
  const [dataNow, setDataNow] = useState();
  const [search, setSearch] = useState(false);
  const [dataPerPage, setDataPerpage] = useState(data);
  const [valueSearch, setValueSearch] = useState(false);
  const indexOfLastPost = currentPage * postsPerPage;
  const indexOfFirstPost = indexOfLastPost - postsPerPage;

  const currentPosts = dataPerPage.slice(indexOfFirstPost, indexOfLastPost);

  const paginate = (pageNumber) => {
    setCurrentPage(pageNumber);
  };
  const onChangeCounter = (event) => {
    setPostsPerPage(event.target.value);
  };

  const onSearch = (event) => {
    if (event.target.value == "") {
      setValueSearch(true);
      window.location.reload();
    } else {
      const result = dataPerPage.find((obj) => {
        return obj.title === event.target.value;
      });
      if (result === undefined) {
        setSearch(true);
      } else {
        setSearch(true);
        setDataNow([result]);
      }
    }
  };

  return (
    <div className="bg-blue-50">
      <Head>
        <title>Moduit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavbar />
      <div className="mx-72">
        <div class="flex space-x-60">
          <h1 className="text-gray-700 text-lg">Question2</h1>
          <div class="flex space-x-72"></div>

          <div class="flex justify-center">
            <div class="mb-3 xl:w-96">
              <div class="input-group relative flex flex-wrap items-stretch w-full mb-4">
                <input
                  type="search"
                  class="form-control relative flex-auto min-w-0 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                  placeholder="Search by product name"
                  aria-label="Search"
                  onChange={onSearch}
                  aria-describedby="button-addon2"
                />
                <button
                  type="button"
                  class="flex absolute inset-y-0 right-0 items-center pr-3"
                >
                  <Image
                    src="/search.svg"
                    alt="Moduit"
                    width={30}
                    height={10}
                  />
                </button>
              </div>
            </div>
          </div>
        </div>

        <div class="flex flex-col mt-10">
          <table class="divide-y divide-gray-300" id="dataTable">
            <thead class="bg-gray-50">
              <tr>
                <th class="px-6 py-2 text-xs text-gray-500">Product Name</th>
                <th class="px-6 py-2 text-xs text-gray-500">Product Code</th>
                <th class="px-6 py-2 text-xs text-gray-500">Category</th>
                <th class="px-6 py-2 text-xs text-gray-500">Descritption</th>
                <th class="px-6 py-2 text-xs text-gray-500">Tags</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-500">
              {search && dataNow === undefined ? (
                <h1>Data tidak ditemukan</h1>
              ) : search ? (
                dataNow.map((item, index) => {
                  return (
                    <tr class="whitespace-nowrap">
                      <td class="py-4 ">
                        <div class="text-sm text-gray-900">{item.title}</div>
                      </td>
                      <td class="py-4 ">
                        <div class="text-sm text-gray-900">{item.id}</div>
                      </td>
                      <td class="py-4r">
                        <div class="text-sm text-gray-500">{item.footer}</div>
                      </td>
                      <td class="text-sm resize-none text-gray-500">
                        {item.description.slice(0, 80)}..
                      </td>
                      <td class="px-6 py-4">
                        {item.tags == undefined ? (
                          ""
                        ) : (
                          <ul class="list-disc">
                            {item.tags.map((i, index) => {
                              return <li>{i}</li>;
                            })}
                          </ul>
                        )}
                      </td>
                    </tr>
                  );
                })
              ) : (
                currentPosts.map((item, index) => {
                  return (
                    <tr class="whitespace-nowrap">
                      <td class="py-4 ">
                        <div class="text-sm text-gray-900">{item.title}</div>
                      </td>
                      <td class="py-4 ">
                        <div class="text-sm text-gray-900">{item.id}</div>
                      </td>
                      <td class="py-4r">
                        <div class="text-sm text-gray-500">{item.footer}</div>
                      </td>
                      <td class="text-sm resize-none text-gray-500">
                        {item.description.slice(0, 80)}..
                      </td>
                      <td class="px-6 py-4">
                        {item.tags == undefined ? (
                          ""
                        ) : (
                          <ul class="list-disc">
                            {item.tags.map((i, index) => {
                              return <li>{i}</li>;
                            })}
                          </ul>
                        )}
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
        <div class="pt-20 flex space-x-8">
          <Pagination
            paginate={paginate}
            postsPerPage={postsPerPage}
            item={data.length}
          />

          <div class="flex space-x-24">
            <div class="flex space-x-20" />
            <div>
              {" "}
              <h1>Show</h1>
            </div>

            <select
              id="countries"
              onChange={onChangeCounter}
              class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            >
              <option selected value="8">
                8
              </option>
              <option value="10">10</option>
            </select>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
